# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
availableSecrets:
  secretManager:
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-token/versions/latest
      env: BROWSERSTACK_ACCESS_KEY
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-username/versions/latest
      env: BROWSERSTACK_USERNAME

logsBucket: gs://ravelin-cloudbuild-logs
options:
  logging: GCS_ONLY

steps:
  - id: npm_install
    name: gcr.io/cloud-builders/npm
    args:
      - install

  - id: npm_run_build
    name: gcr.io/cloud-builders/npm
    args:
      - run
      - build

  - id: npm_run_test
    name: eu.gcr.io/ravelin-builds/chromium
    dir: /workspace
    secretEnv:
      - BROWSERSTACK_ACCESS_KEY
      - BROWSERSTACK_USERNAME
    args:
      - npm
      - run
      - test
