# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
substitutions:
  _NODE: node:18-alpine

availableSecrets:
  secretManager:
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-token/versions/latest
      env: BROWSERSTACK_ACCESS_KEY
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-username/versions/latest
      env: BROWSERSTACK_USERNAME
    - versionName: projects/ravelin-builds/secrets/ci-ngrok-token/versions/latest
      env: NGROK_AUTH_TOKEN
    - versionName: projects/ravelin-builds/secrets/github-token/versions/latest
      env: GITHUB_TOKEN

logsBucket: gs://ravelin-cloudbuild-logs
options:
  logging: GCS_ONLY

steps:
  - id: install
    name: $_NODE
    entrypoint: npm
    args:
      - install

  - id: build
    name: $_NODE
    entrypoint: npm
    args:
      - run
      - build

  - id: browserstack
    name: $_NODE
    waitFor:
      - build
    entrypoint: npm
    env:
      - PARALLEL=5
      - HEAD_BRANCH=$_HEAD_BRANCH
      - COMMIT_SHA=$COMMIT_SHA
      - BUILD_ID=$BUILD_ID
      - HEAD_REPO_URL=$_HEAD_REPO_URL
    secretEnv:
      - BROWSERSTACK_ACCESS_KEY
      - BROWSERSTACK_USERNAME
      - NGROK_AUTH_TOKEN
      - GITHUB_TOKEN
    args:
      - run
      - test:integration

  - id: gcb2gh
    waitFor: ["-"]
    name: "gcr.io/cloud-builders/docker"
    secretEnv: [GITHUB_TOKEN]
    args: [
      "run", "--name", "gcb2gh", "--detach",
      # Configure: the GitHub repo.
      "--env", "GITHUB_TOKEN",
      "--env", "GITHUB_USER=unravelin",
      "--env", "GITHUB_REPO=ravelinjs",
      # Configure: the build manifest.
      "--mount", "type=bind,source=/workspace,target=/workspace,bind-propagation=rprivate",
      "--env", "BUILD_MANIFEST=/workspace/.cloudbuild/ci.yaml",
      # GCB specifics.
      "--env", "BUILD_ID=$BUILD_ID",
      "--env", "PROJECT_ID=$PROJECT_ID",
      "--env", "COMMIT_SHA=$COMMIT_SHA",
      "--mount", "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock,bind-propagation=rprivate",
      "eu.gcr.io/$PROJECT_ID/gcb2gh",
    ]
