# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
tags:
  - ravelinjs

substitutions:
  _NODE: node:22.16.0-bookworm-slim
  _RCLONE_IMAGE: europe-docker.pkg.dev/ravelin-builds/container/dockerhub/rclone/rclone:1.61.1

logsBucket: gs://ravelin-cloudbuild-logs
options:
  logging: GCS_ONLY
  pool:
    name: projects/ravelin-builds/locations/europe-west1/workerPools/c3-highcpu-8

steps:
  - id: mkcert
    name: $_NODE
    env:
      - CAROOT=/workspace/certs
    script: |
      #! /usr/bin/env sh
      set -e
      apt-get update
      apt-get install -y --no-install-recommends ca-certificates curl libnss3-tools
      curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
      chmod +x mkcert-v*-linux-amd64
      mv mkcert-v*-linux-amd64 /usr/local/bin/mkcert
      mkdir ./certs
      mkcert -install
      cd ./certs
      mkcert localhost

  - id: install
    name: $_NODE
    script: |
      #! /usr/bin/env sh
      HUSKY=0 npm install

  - id: build
    name: $_NODE
    script: |
      #! /usr/bin/env sh
      npm run build

  - id: e2e
    name: $_NODE
    env:
      - E2E_NAME_ON_CARD=$_NAME_ON_CARD
      - E2E_RSA_KEY=$_RSA_KEY
      - E2E_CIPHERTEXT_FILE=/workspace/cipher.txt
      - NODE_EXTRA_CA_CERTS=/workspace/certs/rootCA.pem
      - CHROME_BIN=/usr/bin/chromium
    script: |
      #! /usr/bin/env sh
      set -e
      apt-get update
      apt-get install -y --no-install-recommends chromium
      npm run test:e2e

  - id: upload_cipher
    name: "$_RCLONE_IMAGE"
    env:
      - BUILD_ID=$BUILD_ID
    script: |
      #! /usr/bin/env sh
      rclone \
        --config="" \
        --gcs-bucket-policy-only \
        copyto \
        /workspace/cipher.txt \
        :gcs:ravelinjs-integration-tests/$BUILD_ID/cipher.txt
