# yaml-language-server: $schema=https://json.schemastore.org/cloudbuild.json
tags:
  - ravelinjs

substitutions:
  _NODE: node:22.16.0-alpine
  _RCLONE_IMAGE: europe-docker.pkg.dev/ravelin-builds/container/dockerhub/rclone/rclone:1.61.1

availableSecrets:
  secretManager:
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-token/versions/latest
      env: BROWSERSTACK_ACCESS_KEY
    - versionName: projects/ravelin-builds/secrets/ci-browserstack-username/versions/latest
      env: BROWSERSTACK_USERNAME
    - versionName: projects/ravelin-builds/secrets/ci-ngrok-token/versions/latest
      env: NGROK_AUTHTOKEN

logsBucket: gs://ravelin-cloudbuild-logs
options:
  logging: GCS_ONLY
  pool:
    name: projects/ravelin-builds/locations/europe-west1/workerPools/c3-highcpu-8

steps:
  - id: npm_install
    name: $_NODE
    script: |
      #! /usr/bin/env sh
      HUSKY=0 npm install

  - id: npm_run_build
    name: $_NODE
    script: |
      #! /usr/bin/env sh
      npm run build

  - id: create_certificates
    name: $_NODE
    env:
      - CAROOT=/workspace/certs
    script: |
      #! /usr/bin/env sh
      set -e
      mkdir ./certs
      apk add mkcert --no-cache --repository=http://dl-cdn.alpinelinux.org/edge/testing/
      mkcert -install
      cd ./certs
      mkcert localhost

  - id: npm_run_test_integration
    name: $_NODE
    env:
      - HEAD_BRANCH=$BRANCH_NAME
      - COMMIT_SHA=$COMMIT_SHA
      - BUILD_ID=$BUILD_ID
      - E2E_NAME_ON_CARD=$_NAME_ON_CARD
      - E2E_RSA_KEY=$_RSA_KEY
      - E2E_CIPHERTEXT_FILE=/workspace/cipher.txt
      - NODE_EXTRA_CA_CERTS=/workspace/certs/rootCA.pem
    secretEnv:
      - BROWSERSTACK_ACCESS_KEY
      - BROWSERSTACK_USERNAME
      - NGROK_AUTHTOKEN
    script: |
      #! /usr/bin/env sh
      npm run test:integration

  - id: upload_cipher
    name: "$_RCLONE_IMAGE"
    env:
      - BUILD_ID=$BUILD_ID
    script: |
      #! /usr/bin/env sh
      rclone \
        --config="" \
        --gcs-bucket-policy-only \
        copyto \
        /workspace/cipher.txt \
        :gcs:ravelinjs-integration-tests/$BUILD_ID/cipher.txt
